version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
    - 6379:6379
  app:
    build: .
    volumes:
    - ./scripts:/var/broc-api/scripts
    entrypoint: ["sh", "-c"]
    command: ["./scripts/wait-for.sh redis:6379 && java -jar broc-api-app.jar server config.yml"]
    ports:
    - "8000:8000"
    - "8001:8001"
    depends_on:
    - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8002:8002
